SELECT * FROM DimProduct

SELECT
	BrandName AS 'Marca',
	COUNT(BrandName) AS 'Total por Marca' -- QUANDO COLOCAMOS UMA FUNÇÃO DE AGRUPAMENTO JUNTO COM UMA COLUNA COMO NESTE CASO O SQL ESPERA UM GROUP BY CASO NÃO COLOQUEMOS É DADO COMO ERRO
FROM
	DimProduct
GROUP BY
	BrandName
HAVING
	COUNT(BrandName) >= 200