-- Combine as duas funções CHARINDEX e SUBSTRING para extrair de forma automática qualquer sobrenome
-- 1° PASSO: É Sempre descobrir qual padrão
-- [PADRÃO] ESPAÇO SEPARA O SOBRENOME DO NOME, DESCOBRIR QUAL A POSIÇÃO DO ESPAÇO


-- DESCUBRA A POSIÇÃO EM QUE COMEÇA O SOBRENOME UTILIZANDO A FUNÇÃO CHARINDEX
-- 2 Argumentos
-- 1. QUAL 'CARACTER' OU 'TEXTO' QUE QUERO SABER A POSIÇÃO
-- 2. TEXTO ONDE VAMOS ACHAR O CARACTER
SELECT CHARINDEX(' ', 'Bernardo Cavalcanti') AS 'Posição'


--SELECT SUBSTRING('Bernardo Cavalcanti', CHARINDEX(' ', 'Bernardo Cavalcanti') +1, 10) AS 'Nome'
--COLOCANDO CHARINDEX DENTRO DO SEGUNDO ARGUMENTO +1, ELE SEMPRE NOS RETORNA A PRIMEIRA POSIÇÃO DEPOIS DO ESPAÇO [+1]
SELECT CHARINDEX(' ', 'Bernardo Cavalcanti') AS 'Posição'
SELECT SUBSTRING('Bernardo Cavalcanti', CHARINDEX(' ', 'Bernardo Cavalcanti') +1, 10) AS 'SOBRENOME'

-- MESMO EXEMPLO COM NOME: 'Victor Alejandro'
SELECT CHARINDEX(' ', 'Victor Alejandro') AS 'Posição'
SELECT SUBSTRING('Victor Alejandro', CHARINDEX(' ', 'Victor Alejandro') +1, 10) AS 'SOBRENOME'

-- EXTRAIA O SOBRENOME DA RAQUE UTILIZANDO A FUNÇÃO SUBSTRING
-- PEDE 3 ARGUMENTOS
-- 1. TEXTO ONDE VAMOS EXTRAIR AS INFORMAÇÕES
-- 2. A POSIÇÃO INICIAL QUE EU QUERO PEGAR
-- 3. QUANTIDADE DE CARACTERES QUE EU QUERO A PARTIR DO DA POSIÇÃO INICIAL

SELECT CHARINDEX ('Moreno', 'Raquel Moreno') -- ENCONTRA O ÍNDICE OU A POSIÇÃO DO TEXTO
SELECT SUBSTRING ('Raquel Moreno', 8, 6) -- EXTRAI O TEXTO A PARTIR DE UMA POSIÇÃO, DEPOIS UTILIZANDO QUANTIDADE DE CARACTERES
