-- Exercício 02.
/*A COLUNA STYLENAME DA TABELA DIMPRODUCT POSSUI ALGUNS CÓDIGOS IDENTIFICADOS POR NÚMEROS DISTINTOS, 
QUE VÃO DE 0 ATÉ 9, COMO PODE SER VISTO NO EXEMPLO ABAIXO PORÉM, O SETOR DE CONTROLE DECIDIU ALTERAR A 
IDENTIFICAÇÃO DO STYLENAME, E EM VEZ DE USAR NÚMEROS, A IDEIA AGORA É PASSAR A USAR LETRAS PARA SUBSTITUIR OS NÚMEROS, 
CONFORME EXEMPLO ABAIXO: 0 -> A, 1 -> B, 2 -> C, 3 -> D, 4 -> E, 5 -> F, 6 -> G, 7 -> H, 8 -> I, 9 - J 
É DE SUA RESPONSABILIDADE ALTERAR OS NÚMEROS POR LETRAS NA COLUNA STYLENAME DA TABELA DIMPRODUCT. 
UTILIZE UMA FUNÇÃO QUE PERMITA FAZER ESSAS SUBSTITUIÇÕES DE FORMA PRÁTICA E RÁPIDA
*/

SELECT 
	productName,
	styleName,
	TRANSLATE(styleName, '0123456789', 'ABCDEFGHIJ')
FROM 
	dimProduct

-- PRIMEIRO ARGUMENTO: TEXTO, VARIÁVEL OU NOME DA COLUNA ONDE QUEREMOS MODIFICAR
-- SEGUNDO ARGUMENTO: TEXTO ANTIGO (PRECISA ESTAR NA ORDEM CORRETA)
-- TERCEIRO ARGUMENTO: TEXTO NOVO (NOVA SEQUENCIA DE CARACTERES ONDE VAI SER FEITA A SUBISTITUIÇÃO)
