-- TRANSLATE e STUFF: OUTRAS FUNÇÕES DE SUBSTITUIÇÃO

-- TRANSLATE: SUBSTITUI CADA CARACTERE NA ORDEM ENCONTRADA

SELECT TRANSLATE('10.241/444.124k23/1', './k', '---')
-- [PRIMEIRAS ASPAS] POR ORDEM: Passamos o Código 
-- [SEGUNDA ASPAS] Texto que queremos substituir | Precisa estar na ordem certa
-- [TERCEIRA ASPAS]Nova sequencia de caracteres para que ele possa substituir!

SELECT TRANSLATE('ABCD-490123', 'ABCD', 'WXYZ')

-- FUNÇÃO STUFF
-- ELA PEDE 4 ARGUMENTOS:
-- 1: TEXTO QUE EU QUERO SUBSTITUIR
-- 2: QUAL POSIÇÃO COMEÇA ESSE TEXTO
-- 3: QUANTOS CARACTERES TEM O TEXTO QUE EU QUERO SUBSTITUIR
-- 4: QUAL VAI SER O NOVO TEXTO

SELECT STUFF('VBA Impressionador', 1, 3, 'Excel')
SELECT STUFF('VBA Impressionador', 1, 3, 'Python')

--NESTE CASO EU QUERO SUBSTITUIR QUALQUER PALAVRA QUE TENHA 3 CARACTERES PELO ULTIMO TEXTO QUE NO CASO É NOSSO ULTIMO ARGUMENTO

SELECT 
	STUFF('MT98-MOTO G', 1, 2, 'CEL'),
	STUFF('AP01-IPHONE', 1, 2, 'CEL'),
	STUFF('SS61-SAMSUNG GALAXY', 1, 2, 'CEL')
