-- MANIPULANDO STRINGS E DATAS NO SQL
-- AULA 4. FUNÇÃO LEFT E RIGHT
-- LEFT > EXTRAI UMA DETERMINADA QUANTIDADE DE CARACTERES DE UM TEXTO, DA ESQUERDA PARA DIREITA
-- RIGHT > EXTRA UMA DETERMINADA QUANTIDADE DE CARACTERES DE UM TEXTO, DA DIREITA PARA ESQUERDA

-- FAÇÁ UMA CONSULTA À TABELA DE DimProduct E DIVIDA A COLUNA DE StyleName EM 2 PARTES

SELECT * FROM DimProduct

-- NOS É PEDIDO 2 ARGUMENTOS
-- PRIMEIRO: O TEXTO DE ONDE QUEREMOS EXTRAIR OS CARACTERES
-- SEGUNDO: QUANTIDADE DE CARACTERES
SELECT LEFT('Product0101001', 7)
SELECT RIGHT('Product0101001', 7)

-- FAZENDO A FUNÇÃO EM TODAS AS LINHAS DA MINHA TABELA
SELECT
	ProductName AS 'Produto',
	UnitPrice AS 'Preço',
	LEFT(StyleName, 7) AS 'Cód. 1',
	RIGHT(StyleName, 7) AS 'Cód. 2'
FROM
	DimProduct
