-- AULA 005. REPLACE: SUBSTITUI UM DETERMINADO TEXTO POR OUTRO TEXTO
-- NO TEXTO 'O EXCEL É O MELHOR', SUBSTITUA 'EXCEL' POR 'SQL'

SELECT 'O EXCEL É O MELHOR'

--SÃO 3 ARGUMENTOS:
-- I.O TEXTO ONDE TEM A INFORMAÇÃO QUE QUEREMOS SUBSTITUIR
-- II. O TEXTO ANTIGO
-- III. O TEXTO NOVO
SELECT REPLACE('O EXCEL É O MELHOR', 'EXCEL', 'SQL')

--CRIE UMA CONSULTA A PARTIR DE DimCustomer ONDE VOCE RETORNA O NOME COMPLETO DOS CLIENTES, A COLUNA DE SEXO (ABREVIADA) E UMA OUTRA COLUNA DE SEXO SUBSTITUINDO M POR F
SELECT * FROM DimCustomer

SELECT
	FirstName AS 'Nome',
	LastName AS 'Sobrenome',
	Gender AS 'Sexo (Abrev)',
	REPLACE(Gender, 'M', 'Masculino') AS 'Sexo'
FROM
	DimCustomer
