/* O SETOR DE TI ESTÁ CRIANDO UM SISTEMA PARA ACOMPANHAMENTO INDIVIDUAL DE CADA FUNCIONÁRIO DA 
EMPRESA CONTOSO. CADA FUNCIONÁRIO RECEBERÁ UM LOGIN E SENHA. 
O LOGIN DE CADA FUNCIONÁRIO SERÁ O ID DO E-MAIL.

JÁ A SENHA SERÁ:
--X O FIRSTNAME + O DIA DO ANO EM QUE O FUNCIONÁRIO NASCEU [EM MAIÚSCULA. POR EXEMPLO]: 
--X E-MAIL: MARK0@CONTOSO.COM
--X NASCIMENTO: 15/01/1990 
DEVERÁ TER A SEGUINTE SENHA:

LOGIN: MARK0 -- ID EMAIL
SENHA: MARK15 -- FIRSTNAME + DIA DO ANO DO NASCIMENTO
*/

--1. LOGIN SÃO OS CARACTERES ANTES DO '@'

--2. QUANTIDADE DE CARACTERES VAI SER SEMPRE O @ QUE É ONDE TERMINA PRIMEIRA PA

SELECT
	firstName + ' ' + lastName AS 'Nome Completo',
	emailAddress AS 'E-mail',
	LEFT(emailAddress, CHARINDEX('@', emailAddress)-1) AS 'Login',
	UPPER(FirstName + DATENAME(DAYOFYEAR, BirthDate)) AS 'Password'
FROM
	DimEmployee

-- ENTENDENDO O CÓDIGO:
-- ESTOU PEGANDO TODOS OS CARACTERES COMEÇANDO DA ESQUERDA E INDO ATÉ A POSIÇÃO DO '@'
-- PORÉM EU QUERO OS CARACTERES ATÉ UMA POSIÇÃO ANTES DO '@' POIS NÃO QUERO QUE ELE APAREÇA NO LOGIN
-- POR ULTIMO CONCATENAMOS O PRIMEIRO NOME COM O DIA DO ANO DO NASCIMENTO DO EMPREGADO
