-- GETDATE: Retorna a data/hora atual do sistema
-- SYSDATETIME: Retorna a data/hora atual do sistema(mais preciso que a GETDATE)
-- DATENAME e DATEPART: Retorna informações (dia, mes, ano, semana, etc) de uma data 

SELECT GETDATE()
SELECT SYSDATETIME()

--DATENAME
--RETORNA O RESULTADO EM FORMATO DE TEXTO
DECLARE @varData DATETIME = GETDATE() -- DATA ATUAL QUE VOCE RODAR O CÓDIGO

SELECT 
	DATENAME(DAY, @varData) AS 'DIA ATUAL',
	DATENAME(MONTH, @varData) AS 'MES ATUAL',
	DATENAME(YEAR, @varData) AS 'ANO ATUAL',
	DATENAME(DAYOFYEAR, @varData) AS 'DIA DO ANO',
	DATENAME(WEEKDAY, @varData) AS 'DIA DA SEMANA'

-- DATEPART
--RETORNA O RESULTADO EM FORMATO DE NUMERO
SELECT 
	DATEPART(DAY, @varData) AS 'DIA ATUAL',
	DATEPART(MONTH, @varData) AS 'MES ATUAL',
	DATEPART(YEAR, @varData) AS 'ANO ATUAL',
	DATEPART(DAYOFYEAR, @varData) AS 'DIA DO ANO',
	DATEPART(WEEKDAY, @varData) AS 'DIA DA SEMANA'

-- SABENDO QUAL TIPO DE DADOS QUE É RETORNADO EM CADA UMA DAS FUNÇÕES UTILIZAMOS:
SELECT 
	SQL_VARIANT_PROPERTY (DATENAME(DAY, @varData), 'BaseType') AS 'Tipo de Dado', -- RETORNAR NVARCHAR, TIPO TEXTO
	SQL_VARIANT_PROPERTY (DATEPART(DAY, @varData), 'BaseType') AS 'Tipo de Dado'-- RETORNA INT, TIPO NUMERO
