/* 
QUANDO ESTAMOS MANIPULANDO TABELAS, É IMPORTANTE PENSAR EM COMO OS DADOS SERÃO 
APRESENTADOS EM UM RELATÓRIO. IMAGINE OS NOMES DOS PRODUTOS DA TABELA DIMPRODUCT. OS 
TEXTOS SÃO BEM GRANDES E PODE SER QUE MOSTRAR OS NOMES COMPLETOS DOS PRODUTOS NÃO SEJA A 
OPÇÃO MAIS INTERESSANTE, POIS PROVAVELMENTE NÃO VÃO CABER EM UM GRÁFICO E A VISUALIZAÇÃO 
FICARÁ RUIM
*/

SELECT productName FROM DimProduct

/*
A. SEU GESTOR TE PEDE PARA LISTAR TODOS OS PRODUTOS PARA QUE SEJA CRIADO UM GRÁFICO PARA SER 
APRESENTADO NA REUNIÃO DIÁRIA DE EQUIPE. FAÇA UMA CONSULTA À TABELA DIMPRODUCT QUE 
RETORNE (1) O NOME DO PRODUTO E (2) A QUANTIDADE DE CARACTERES QUE CADA PRODUTO TEM, 
E ORDENE ESSA TABELA DO PRODUTO COM A MAIOR QUANTIDADE DE CARACTERES PARA A MENOR.
*/


SELECT 
	productName AS 'Produto',
	LEN(productName) AS 'Caracteres'
FROM
	dimProduct

-- B. QUAL A MÉDIA DE CARACTERES DOS NOMES DOS PRODUTOS?
SELECT
	AVG(LEN(productName)) AS 'Média Caracteres'
FROM 
	DimProduct

/* C.ANALISE A ESTRUTURA DOS NOMES DOS PRODUTOS E VERIFIQUE SE SERIA POSSÍVEL REDUZIR O TAMANHO DO NOME DOS PRODUTOS. 
(DICA: EXISTEM INFORMAÇÕES REDUNDANTES NOS NOMES DOS PRODUTOS? SERIA POSSÍVEL SUBSTITUÍ-LAS?)*/

-- REPLACE: PERMITE SUBSTITUIR UM TEXTO POR OUTRO
-- PRIMEIRO ARGUMENTO: TEXTO ONDE CONTÉM A INFORMAÇÃO QUE QUEREMOS TROCAR
-- SEGUNDO ARGUMENTO: TEXTO ANTIGO
-- TERCEIRO ARGUMENTO: TEXTO NOVO
-- PARA CADA brandName SERÁ SUBSTITUÍDO POR VALOR VAZIO
SELECT
	productName,
	brandName,
	colorName,
	REPLACE(REPLACE(ProductName, BrandName, ''), ColorName, '')
FROM
	DimProduct

-- D. QUAL É A MÉDIA DE CARACTERES NESSE NOVO CENÁRIO?
SELECT
	AVG(LEN(REPLACE(REPLACE(ProductName, BrandName, ''), ColorName, ''))) 
FROM
	DimProduct
