-- EXERCÍCIO 004
/* A TABELA DIMCUSTOMER POSSUI O PRIMEIRO REGISTRO DE VENDAS NO ANO DE 2001. COMO FORMA DE RECONHECEROS CLIENTES QUE COMPRARAM NESSE ANO, 
O SETOR DE MARKETING SOLICITOU A VOCÊ QUE RETORNASSE UMA TABELA COM TODOS OS CLIENTES QUE FIZERAM A SUA PRIMEIRA COMPRA NESTE ANO PARA QUE SEJA ENVIADO UMA ENCOMENDA COM UM PRESENTE PARA CADA UM. 

PARA FAZER ESSE FILTRO, VOCÊ PODE UTILIZAR A COLUNA DATEFIRSTPURCHASE, QUE CONTÉM A INFORMAÇÃO DA DATA DA PRIMEIRA COMPRA DE CADA
CLIENTE NA TABELA DIMCUSTOMER. 

VOCÊ DEVERÁ RETORNAR AS COLUNAS DE FIRSTNAME, EMAILADDRESS, ADDRESSLINE1 E DATEFIRSTPURCHASE DA TABELA DIMCUSTOMER,
CONSIDERANDO APENAS OS CLIENTES QUE FIZERAM A PRIMEIRA COMPRA NO ANO DE 2001.
*/

SELECT * FROM dimCustomer

SELECT
	firstName,
	emailAddress,
	addressLine1,
	dateFirstPurchase
FROM 
	dimCustomer
WHERE YEAR(dateFirstPurchase) = 2001
ORDER BY dateFirstPurchase 
