/* A TABELA DIMEMPLOYEE POSSUI UMA INFORMAÇÃO DE DATA DE CONTRATAÇÃO (HIREDATE). A ÁREA DE RH, NO ENTANTO, PRECISA DAS INFORMAÇÕES DESSAS DATAS DE FORMA SEPARADA EM DIA, MÊS E ANO, POIS SERÁ FEITA UMA AUTOMATIZAÇÃO PARA CRIAÇÃO DE UM RELATÓRIO DE RH, E FACILITARIA MUITO SE ESSAS INFORMAÇÕES ESTIVESSEM SEPARADAS EM UMA TABELA. 

VOCÊ DEVERÁ REALIZAR UMA CONSULTA À TABELA DIMEMPLOYEE E RETORNAR UMA TABELA CONTENDO AS SEGUINTES INFORMAÇÕES: FIRSTNAME, EMAILADDRESS, HIREDATE, ALÉM DAS COLUNAS DE DIA, MÊS E ANO DE CONTRATAÇÃO. 

OBS1: A COLUNA DE MÊS DEVE CONTER O NOME DO MÊS POR EXTENSO, E NÃO O NÚMERO DO MÊS. 

OBS2: LEMBRE-SE DE NOMEAR CADA UMA DESSAS COLUNAS EM SUA CONSULTA PARA GARANTIR QUE O ENTENDIMENTO DE CADA INFORMAÇÃO FICARÁ 100% CLARO */

SELECT
	firstName,
	EmailAddress,
	HireDate,
	DAY(HireDate) AS 'Dia',
	DATENAME(MONTH, HireDate) AS 'Month',
	YEAR(HireDate) AS 'Ano' 
FROM 
	dimEmployee
