-- CASE: A FUNÇÃO CASE PERMITE TRATAR CONDIÇÕES NO SQL

/*  CASE
		WHEN TESTE_1 THEN 'RESULTADO_1'
		WHEN TESTE_2 THEN 'RESULTADO_2'
		ELSE 'RESULTADO_3'
	END

EXEMPLO:
-- APROVADO: NOTA >= 6
-- PROVA FINAL: NOTA ENTRE 4 E 6
-- REPROVADO: < 4   */


DECLARE @varNota FLOAT = 8.5

SELECT
	CASE
		WHEN @varNota >= 6 THEN 'APROVADO'
		WHEN @varNota >= 4 THEN 'PROVA FINAL'
		ELSE 'REPROVADO'
	END AS 'SITUAÇÃO'


-- CLASSIFIQUE O PRODUTO DE ACORDO COM O SEU PREÇO
-- PREÇO >= 40.000: LUXO
-- PREÇO >= 10.000: ECONÔMICO
-- PREÇO < 10.000: BÁSICO

DECLARE @varPreco FLOAT = 50000

SELECT
	CASE
		WHEN @varPreco >= 40000 THEN 'LUXO'
		WHEN @varPreco >= 10000 THEN 'ECONÔMICO'
		ELSE 'BÁSICO'
	END AS 'PRODUTO'
