-- IS NULL: TRATANDO VALORES NULOS

SELECT * FROM DimGeography

-- ISNULL PEDE-SE DOIS ARGUMENTOS:
-- PRIMEIRO: QUAL A EXPRESSÃO/COLUNA QUE QUERO VERIFICAR SE TEM VALOR NULO OU NÃO
-- SEGUNDO: E QUAL SERIA O VALOR ALTERNATIVO
SELECT
	GeographyKey,
	ContinentName,
	CityName,
	ISNULL(CityName, 'Local Desconhecido') --PEDE-SE DOIS ARGUMENTOS
FROM
	DimGeography
