-- COLLATE - EXAMPLE

/*
CRIAMOS UM BANCO DE DADOS COM AS SEGUINTES CONFIGURAÇÕES:
CI - CASE INSENTIVE, ONDE, NÃO VAI DIFERENCIAR MAIÚSCULA DE MINÚSCULA;
AS - ACCENT SENSITE, ONDE, VAI DIFERENCIAR O NOME PELA ACENTUAÇÃO
*/

CREATE DATABASE BD_Collation
COLLATE Latin1_General_CI_AS 

/*AQUI CASO NÃO IDENTIFICARMOS QUAL COLLATE, A TABELA HERDA COLLATE DO BANCO DE DADOS */
/*ENTÃO CONFIGURAMOS A COLUNA NOME PARA TER UM COLLATION DIFERENTE DA CONFIGURAÇÃO INICIAL*/
CREATE TABLE Tabela(
ID INT, 
Nome VARCHAR(100)COLLATE Latin1_General_CS_AS)

INSERT INTO Tabela(ID, Nome)
VALUES
	(1, 'Matheus'),
	(2, 'Marcela'),
	(3, 'marcos'),	
	(4, 'MAurício'),
	(5, 'Marta'),
	(6, 'Miranda'),
	(7, 'Melissa'),
	(8, 'Lucas'),
	(9, 'luísa'),
	(10, 'Pedro')


SELECT * FROM Tabela

/*USANDO COLLATE NA PRÁTICA*/

GO
SELECT
	ID, 
	Nome
FROM Tabela
WHERE Nome = 'Marcela'

/*AGORA COM A COLUNA CASE SENSITIVE QUANDO 'Marcela' ESTIVER DIGITADO DE FORMA DIFERENTE DA TABELA, NÃO OCORRERÁ A VISUALIZAÇÃO DESTE ITEM*/

/*PARA QUE QUALQUER TIPO DE MARCELA FUNCIONE NESSE CASO, PODEMOS FAZER DA SEGUINTE FORMA: */

GO
SELECT
	ID, 
	Nome
FROM Tabela
WHERE Nome COLLATE Latin1_General_CI_AS = 'MARCELA'
